### ISSUE TITLE
3D Models 

### ISSUE THREAD

**Issue by elliot-winch** [elliot-winch/GameOfDrones#8]
- Some target for the enemies to attack (currently it's a purple balloon)
- Some graphic for the cubes
- A platform (currently we are using the default white plane)

**Comment by elliot-winch** [comment]
- Wall (currently using default unity cube)

**Comment by elliot-winch** [comment]
- Bullet for drones / players / turrets to shoot ( could all be the same thing). Easy to model (probably just a cylinder) but texturing to make it look good might take time.

**Comment by sgg314** [comment]
3D Models:
- Target for enemies to attack
- Better turret placement labels
- Projectile (better than a disc)

**Comment by sgg314** [comment]
Later 3D Models
- New Enemies
- New guns
- Location

**Comment by elliot-winch** [comment]
Moved to #28
